import { defineObject, FieldType } from 'twenty-sdk/define';

import {
  CAMPAIGN_AUDIENCE_FIELD_ID,
  CAMPAIGN_CONTENT_FIELD_ID,
  CAMPAIGN_KIND_FIELD_ID,
  CAMPAIGN_KIND_OPTION_IDS,
  CAMPAIGN_MEDIA_FIELD_ID,
  CAMPAIGN_MESSAGE_EN_FIELD_ID,
  CAMPAIGN_MESSAGE_MS_FIELD_ID,
  CAMPAIGN_MESSAGE_ZH_FIELD_ID,
  CAMPAIGN_NAME_FIELD_ID,
  CAMPAIGN_OBJECT_ID,
  CAMPAIGN_OCCASION_FIELD_ID,
  CAMPAIGN_OCCASION_OPTION_IDS,
  CAMPAIGN_PROGRESS_FIELD_ID,
  CAMPAIGN_SEND_ON_FIELD_ID,
  CAMPAIGN_STATUS_FIELD_ID,
  CAMPAIGN_STATUS_OPTION_IDS,
} from 'src/constants/universal-identifiers-v4';
import { CAMPAIGN_KINDS, CAMPAIGN_STATUSES, OCCASIONS } from 'src/shared/campaigns';

// A message for many people at once — a holiday greeting, a newsletter or an
// announcement — sent from your own WhatsApp, one tap per person, in each
// person's language.
export default defineObject({
  universalIdentifier: CAMPAIGN_OBJECT_ID,
  nameSingular: 'campaign',
  namePlural: 'campaigns',
  labelSingular: 'Campaign',
  labelPlural: 'Campaigns',
  description: 'Greetings, newsletters and announcements sent on WhatsApp',
  icon: 'IconSpeakerphone',
  labelIdentifierFieldMetadataUniversalIdentifier: CAMPAIGN_NAME_FIELD_ID,
  fields: [
    { universalIdentifier: CAMPAIGN_NAME_FIELD_ID, type: FieldType.TEXT, name: 'name', label: 'Name', icon: 'IconAbc' },
    {
      universalIdentifier: CAMPAIGN_KIND_FIELD_ID,
      type: FieldType.SELECT,
      name: 'kind',
      label: 'Kind',
      icon: 'IconCategory',
      defaultValue: "'GREETING'",
      options: CAMPAIGN_KINDS.map((k, index) => ({ id: CAMPAIGN_KIND_OPTION_IDS[index], value: k.value, label: k.label, position: index, color: k.color })),
    },
    {
      universalIdentifier: CAMPAIGN_OCCASION_FIELD_ID,
      type: FieldType.SELECT,
      name: 'occasion',
      label: 'Occasion',
      icon: 'IconConfetti',
      isNullable: true,
      defaultValue: "'CUSTOM'",
      options: OCCASIONS.map((o, index) => ({ id: CAMPAIGN_OCCASION_OPTION_IDS[index], value: o.value, label: o.label, position: index, color: o.color as 'gray' })),
    },
    {
      universalIdentifier: CAMPAIGN_STATUS_FIELD_ID,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      icon: 'IconProgress',
      defaultValue: "'DRAFT'",
      options: CAMPAIGN_STATUSES.map((s, index) => ({ id: CAMPAIGN_STATUS_OPTION_IDS[index], value: s.value, label: s.label, position: index, color: s.color })),
    },
    {
      universalIdentifier: CAMPAIGN_SEND_ON_FIELD_ID,
      type: FieldType.DATE,
      name: 'sendOn',
      label: 'Send on',
      description: 'The day it shows on Today, ready to send.',
      icon: 'IconCalendarEvent',
      isNullable: true,
    },
    {
      universalIdentifier: CAMPAIGN_AUDIENCE_FIELD_ID,
      type: FieldType.RAW_JSON,
      name: 'audience',
      label: 'Audience',
      description: 'Who gets it: tags, tenants, workspaces, people added or left out.',
      icon: 'IconUsers',
      isNullable: true,
    },
    { universalIdentifier: CAMPAIGN_MESSAGE_EN_FIELD_ID, type: FieldType.TEXT, name: 'messageEn', label: 'Message (English)', icon: 'IconMessage', isNullable: true },
    { universalIdentifier: CAMPAIGN_MESSAGE_MS_FIELD_ID, type: FieldType.TEXT, name: 'messageMs', label: 'Message (Malay)', icon: 'IconMessage', isNullable: true },
    { universalIdentifier: CAMPAIGN_MESSAGE_ZH_FIELD_ID, type: FieldType.TEXT, name: 'messageZh', label: 'Message (Chinese)', icon: 'IconMessage', isNullable: true },
    {
      universalIdentifier: CAMPAIGN_CONTENT_FIELD_ID,
      type: FieldType.RAW_JSON,
      name: 'content',
      label: 'Newsletter content',
      description: 'Title, intro, stories and sign-off of a newsletter (the messages are built from it).',
      icon: 'IconNews',
      isNullable: true,
    },
    {
      universalIdentifier: CAMPAIGN_MEDIA_FIELD_ID,
      type: FieldType.FILES,
      name: 'media',
      label: 'Photos / video',
      description: 'Sent along with the message (shared from your phone, or copied and pasted on a computer).',
      icon: 'IconPhoto',
      isNullable: true,
      universalSettings: { maxNumberOfValues: 4 },
    },
    {
      universalIdentifier: CAMPAIGN_PROGRESS_FIELD_ID,
      type: FieldType.RAW_JSON,
      name: 'progress',
      label: 'Progress',
      description: 'Who it was sent to or skipped, and when.',
      icon: 'IconChecklist',
      isNullable: true,
    },
  ],
});
