import { defineObject, FieldType } from 'twenty-sdk/define';

import {
  PAYMENT_AMOUNT_FIELD_ID,
  PAYMENT_METHOD_BANK_TRANSFER_OPTION_ID,
  PAYMENT_METHOD_CASH_OPTION_ID,
  PAYMENT_METHOD_CHEQUE_OPTION_ID,
  PAYMENT_METHOD_DUITNOW_OPTION_ID,
  PAYMENT_METHOD_FIELD_ID,
  PAYMENT_METHOD_OTHER_OPTION_ID,
  PAYMENT_NOTES_FIELD_ID,
  PAYMENT_OBJECT_ID,
  PAYMENT_PAID_ON_FIELD_ID,
  PAYMENT_PERIOD_FIELD_ID,
  PAYMENT_RECEIPT_FILE_FIELD_ID,
  PAYMENT_RECEIPT_NUMBER_FIELD_ID,
  PAYMENT_RECEIPT_SENT_AT_FIELD_ID,
  PAYMENT_STATUS_DRAFT_OPTION_ID,
  PAYMENT_STATUS_FIELD_ID,
  PAYMENT_STATUS_ISSUED_OPTION_ID,
  PAYMENT_STATUS_SENT_OPTION_ID,
  PAYMENT_STATUS_VOID_OPTION_ID,
  PAYMENT_TYPE_DEPOSIT_OPTION_ID,
  PAYMENT_TYPE_FIELD_ID,
  PAYMENT_TYPE_RENT_OPTION_ID,
} from 'src/constants/universal-identifiers';
import { PAYMENT_TYPE_UTILITY_DEPOSIT_OPTION_ID } from 'src/constants/universal-identifiers-v2';
import { PAYMENT_STATUS_WAIVED_OPTION_ID } from 'src/constants/universal-identifiers-v3';

// Money received from a tenant: monthly rent or a deposit. Each payment gets
// a receipt (number + PDF) that can be sent to the tenant.
export default defineObject({
  universalIdentifier: PAYMENT_OBJECT_ID,
  nameSingular: 'rentPayment',
  namePlural: 'rentPayments',
  labelSingular: 'Payment',
  labelPlural: 'Payments',
  description: 'Rent or deposit received from a tenant',
  icon: 'IconReceipt',
  labelIdentifierFieldMetadataUniversalIdentifier:
    PAYMENT_RECEIPT_NUMBER_FIELD_ID,
  fields: [
    {
      universalIdentifier: PAYMENT_STATUS_FIELD_ID,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      description:
        'Draft: editable, no receipt number yet. Issued: numbered receipt created but not emailed. Sent: emailed to the tenant. Void: cancelled after issuing (keeps its number). Waived: rent for the month (or what was left of it) not charged; no receipt.',
      icon: 'IconProgress',
      defaultValue: "'DRAFT'",
      options: [
        { id: PAYMENT_STATUS_DRAFT_OPTION_ID, value: 'DRAFT', label: 'Draft', position: 0, color: 'gray' },
        { id: PAYMENT_STATUS_ISSUED_OPTION_ID, value: 'ISSUED', label: 'Issued', position: 1, color: 'orange' },
        { id: PAYMENT_STATUS_SENT_OPTION_ID, value: 'SENT', label: 'Sent', position: 2, color: 'green' },
        { id: PAYMENT_STATUS_VOID_OPTION_ID, value: 'VOID', label: 'Void', position: 3, color: 'red' },
        { id: PAYMENT_STATUS_WAIVED_OPTION_ID, value: 'WAIVED', label: 'Waived', position: 4, color: 'sky' },
      ],
    },
    {
      universalIdentifier: PAYMENT_RECEIPT_NUMBER_FIELD_ID,
      type: FieldType.TEXT,
      name: 'receiptNumber',
      label: 'Receipt no.',
      description: 'Assigned when the receipt is generated, e.g. RCP-2026-0001',
      icon: 'IconHash',
    },
    {
      universalIdentifier: PAYMENT_TYPE_FIELD_ID,
      type: FieldType.SELECT,
      name: 'paymentType',
      label: 'Type',
      icon: 'IconCategory',
      defaultValue: "'RENT'",
      options: [
        {
          id: PAYMENT_TYPE_RENT_OPTION_ID,
          value: 'RENT',
          label: 'Rent',
          position: 0,
          color: 'blue',
        },
        {
          id: PAYMENT_TYPE_DEPOSIT_OPTION_ID,
          value: 'DEPOSIT',
          label: 'Security deposit',
          position: 1,
          color: 'purple',
        },
        {
          id: PAYMENT_TYPE_UTILITY_DEPOSIT_OPTION_ID,
          value: 'UTILITY_DEPOSIT',
          label: 'Utility deposit',
          position: 2,
          color: 'violet',
        },
      ],
    },
    {
      universalIdentifier: PAYMENT_AMOUNT_FIELD_ID,
      type: FieldType.CURRENCY,
      name: 'amount',
      label: 'Amount',
      icon: 'IconCash',
      isNullable: true,
      defaultValue: { amountMicros: null, currencyCode: "'MYR'" },
    },
    {
      universalIdentifier: PAYMENT_PAID_ON_FIELD_ID,
      type: FieldType.DATE,
      name: 'paidOn',
      label: 'Paid on',
      icon: 'IconCalendar',
      isNullable: true,
    },
    {
      universalIdentifier: PAYMENT_PERIOD_FIELD_ID,
      type: FieldType.DATE,
      name: 'rentPeriod',
      label: 'Rent for month',
      description: 'Any date in the month this rent covers (rent only)',
      icon: 'IconCalendarMonth',
      isNullable: true,
    },
    {
      universalIdentifier: PAYMENT_METHOD_FIELD_ID,
      type: FieldType.SELECT,
      name: 'method',
      label: 'Method',
      icon: 'IconCreditCard',
      isNullable: true,
      options: [
        {
          id: PAYMENT_METHOD_BANK_TRANSFER_OPTION_ID,
          value: 'BANK_TRANSFER',
          label: 'Bank transfer',
          position: 0,
          color: 'blue',
        },
        {
          id: PAYMENT_METHOD_DUITNOW_OPTION_ID,
          value: 'DUITNOW',
          label: 'DuitNow',
          position: 1,
          color: 'pink',
        },
        {
          id: PAYMENT_METHOD_CASH_OPTION_ID,
          value: 'CASH',
          label: 'Cash',
          position: 2,
          color: 'green',
        },
        {
          id: PAYMENT_METHOD_CHEQUE_OPTION_ID,
          value: 'CHEQUE',
          label: 'Cheque',
          position: 3,
          color: 'orange',
        },
        {
          id: PAYMENT_METHOD_OTHER_OPTION_ID,
          value: 'OTHER',
          label: 'Other',
          position: 4,
          color: 'gray',
        },
        {
          // The month's rent was taken from the tenant's deposit.
          id: '63cf3adb-4818-4df4-92c9-422f7e61eeca',
          value: 'FROM_DEPOSIT',
          label: 'Paid from deposit',
          position: 5,
          color: 'purple',
        },
      ],
    },
    {
      universalIdentifier: PAYMENT_NOTES_FIELD_ID,
      type: FieldType.TEXT,
      name: 'notes',
      label: 'Notes',
      icon: 'IconNotes',
      isNullable: true,
    },
    {
      universalIdentifier: PAYMENT_RECEIPT_FILE_FIELD_ID,
      type: FieldType.FILES,
      name: 'receiptFile',
      label: 'Receipt PDF',
      icon: 'IconFileTypePdf',
      isNullable: true,
      universalSettings: { maxNumberOfValues: 1 },
    },
    {
      // Exactly what was printed when the receipt was issued (content,
      // wording and template), so later setting changes don't alter how an
      // issued receipt is shown.
      universalIdentifier: '1c96e368-79c7-4634-8b6a-5fdca130778b',
      type: FieldType.RAW_JSON,
      name: 'receiptSnapshot',
      label: 'Receipt snapshot',
      icon: 'IconCamera',
      isNullable: true,
    },
    {
      universalIdentifier: PAYMENT_RECEIPT_SENT_AT_FIELD_ID,
      type: FieldType.DATE_TIME,
      name: 'receiptSentAt',
      label: 'Receipt sent',
      icon: 'IconMailCheck',
      isNullable: true,
      defaultValue: null,
    },
    {
      // Set when a receipt is back-dated to the payment date; otherwise the
      // receipt is dated the day it's issued.
      universalIdentifier: '7445ecc0-c46b-4c5f-a359-d3267934c1fb',
      type: FieldType.DATE,
      name: 'receiptDate',
      label: 'Receipt date',
      description: 'Date printed on the receipt. Empty = the day it was issued.',
      icon: 'IconCalendarEvent',
      isNullable: true,
    },
  ],
});
