import { defineObject, FieldType } from 'twenty-sdk/define';

import {
  PROPERTY_ADDRESS_FIELD_ID,
  PROPERTY_DEPOSIT_FIELD_ID,
  PROPERTY_MONTHLY_RENT_FIELD_ID,
  PROPERTY_NAME_FIELD_ID,
  PROPERTY_NOTES_FIELD_ID,
  PROPERTY_OBJECT_ID,
  PROPERTY_STATUS_FIELD_ID,
  PROPERTY_STATUS_OCCUPIED_OPTION_ID,
  PROPERTY_STATUS_VACANT_OPTION_ID,
  PROPERTY_TYPE_FIELD_ID,
} from 'src/constants/universal-identifiers';

// A rentable unit, e.g. "Block A-3-2" or "No. 12, Jalan Mawar".
export default defineObject({
  universalIdentifier: PROPERTY_OBJECT_ID,
  nameSingular: 'property',
  namePlural: 'properties',
  labelSingular: 'Property',
  labelPlural: 'Properties',
  description: 'A rentable property or unit',
  icon: 'IconHome',
  labelIdentifierFieldMetadataUniversalIdentifier: PROPERTY_NAME_FIELD_ID,
  fields: [
    {
      universalIdentifier: PROPERTY_NAME_FIELD_ID,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Name',
      description: 'Unit name or short address, e.g. Block A-3-2',
      icon: 'IconAbc',
    },
    {
      universalIdentifier: PROPERTY_ADDRESS_FIELD_ID,
      type: FieldType.ADDRESS,
      name: 'propertyAddress',
      label: 'Address',
      icon: 'IconMapPin',
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_MONTHLY_RENT_FIELD_ID,
      type: FieldType.CURRENCY,
      name: 'monthlyRent',
      label: 'Monthly rent',
      icon: 'IconCash',
      isNullable: true,
      defaultValue: { amountMicros: null, currencyCode: "'MYR'" },
    },
    {
      universalIdentifier: PROPERTY_DEPOSIT_FIELD_ID,
      type: FieldType.CURRENCY,
      name: 'depositAmount',
      label: 'Deposit',
      icon: 'IconShieldCheck',
      isNullable: true,
      defaultValue: { amountMicros: null, currencyCode: "'MYR'" },
    },
    {
      universalIdentifier: PROPERTY_STATUS_FIELD_ID,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      icon: 'IconProgress',
      defaultValue: "'VACANT'",
      options: [
        {
          id: PROPERTY_STATUS_VACANT_OPTION_ID,
          value: 'VACANT',
          label: 'Vacant',
          position: 0,
          color: 'gray',
        },
        {
          id: PROPERTY_STATUS_OCCUPIED_OPTION_ID,
          value: 'OCCUPIED',
          label: 'Occupied',
          position: 1,
          color: 'green',
        },
      ],
    },
    {
      universalIdentifier: PROPERTY_TYPE_FIELD_ID,
      type: FieldType.SELECT,
      name: 'propertyType',
      label: 'Type',
      icon: 'IconBuildingCommunity',
      isNullable: true,
      options: [
        { id: '02a9de88-340b-4f13-8a1f-f84ac9fba1ed', value: 'CONDO', label: 'Condo / Apartment', position: 0, color: 'blue' },
        { id: 'f15c2f8b-b772-4d81-b08b-0f16fec2be03', value: 'LANDED', label: 'Landed house', position: 1, color: 'green' },
        { id: '143d2f68-86ba-4daf-96e3-7cf037c39a8f', value: 'SHOP', label: 'Shop / Office', position: 2, color: 'orange' },
        { id: 'b85c42cb-4cf5-448b-86b3-8805ffe56137', value: 'ROOM', label: 'Room', position: 3, color: 'purple' },
      ],
    },
    {
      universalIdentifier: PROPERTY_NOTES_FIELD_ID,
      type: FieldType.TEXT,
      name: 'notes',
      label: 'Notes',
      icon: 'IconNotes',
      isNullable: true,
    },
  ],
});
